
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;

/**
 *
 * @author Luis Hernández
 * 
 * Clase que representa el formulario principal de la aplicación de pedidos.
 * 
 * Permite al usuario ingresar los detalles del pedido, como nombre del medicamento, tipo, cantidad, distribuidor y farmacia destino.
 * 
 * También incluye validaciones de campos y limitación de caracteres.
 * 
 */
public class NewJFrame extends javax.swing.JFrame {

    //Clase que se usara para limitar caracteres en los campos.
    public class LimiteDeCaracteres extends DocumentFilter {

        private int limit;
        
        /**
         * Constructor de la clase LimiteDeCaracteres.
         * @param limit Límite máximo de caracteres permitidos.
         */
        public LimiteDeCaracteres(int limit) {

            this.limit = limit;
        }

        @Override
        public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
            int currentLength = fb.getDocument().getLength();
            int overLimit = (currentLength + text.length()) - limit - length;
            if (overLimit > 0) {
                text = text.substring(0, text.length() - overLimit);
            }
            if (text.isEmpty() || text.length() > 0) {
                super.replace(fb, offset, length, text, attrs);
            }
        }
    }
    /**
     * Constructor de la clase NewJFrame.
     * Inicializa los componentes de la interfaz de usuario y configura las acciones de los botones y campos de texto.
     */
    public NewJFrame() {
        initComponents();
        // Limita NombreMedicamentoText a 50 caracteres
        ((PlainDocument) NombreMedicamentoText.getDocument()).setDocumentFilter(new LimiteDeCaracteres(25));

        // Limita CantidadText a 3 caracteres
        ((PlainDocument) CantidadText.getDocument()).setDocumentFilter(new LimiteDeCaracteres(3));

        // Permite solo números en CantidadText
        CantidadText.addKeyListener(new KeyAdapter() {
            //Permite identificar lo que teclea el usuario
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume();  // Ignora cualquier carácter que no sea (! -> distinto) un dígito
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        NombreMedicamentoText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TipoMedicamentoBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        CantidadText = new javax.swing.JTextField();
        OpcionDistribuidor1 = new javax.swing.JRadioButton();
        OpcionDistribuidor2 = new javax.swing.JRadioButton();
        OpcionDistribuidor3 = new javax.swing.JRadioButton();
        DistribuidorLabel = new javax.swing.JLabel();
        APPLabel = new javax.swing.JLabel();
        Farmacia1 = new javax.swing.JCheckBox();
        Farmacia2 = new javax.swing.JCheckBox();
        FarmaciaLabel = new javax.swing.JLabel();
        CancelButton = new javax.swing.JButton();
        NextButton = new javax.swing.JButton();
        Error1 = new javax.swing.JLabel();
        Error2 = new javax.swing.JLabel();
        Error3 = new javax.swing.JLabel();
        Error4 = new javax.swing.JLabel();
        Error5 = new javax.swing.JLabel();
        InfoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NombreMedicamentoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreMedicamentoTextActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre del medicamento");

        jLabel2.setText("Tipo de Medicamento");

        TipoMedicamentoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--MEDICAMENTO", "Analgésico", "Analéptico", "Anestésico", "Antiácido ", "Antidepresivo", "Antibiótico" }));
        TipoMedicamentoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoMedicamentoBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad");

        CantidadText.setText("0");
        CantidadText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadTextActionPerformed(evt);
            }
        });

        buttonGroup1.add(OpcionDistribuidor1);
        OpcionDistribuidor1.setText("Cofarma");
        OpcionDistribuidor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcionDistribuidor1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(OpcionDistribuidor2);
        OpcionDistribuidor2.setText("Empsephar");

        buttonGroup1.add(OpcionDistribuidor3);
        OpcionDistribuidor3.setText("Cemefar");

        DistribuidorLabel.setText("Distribuidor");

        APPLabel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        APPLabel.setText("APP DE PEDIDOS");

        Farmacia1.setText("Farmacia Principal");

        Farmacia2.setText("Farmacia Filial");

        FarmaciaLabel.setText("Farmacia/as");

        CancelButton.setText("Borrar");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        NextButton.setText("CONFIRMAR");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        InfoButton.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 12)); // NOI18N
        InfoButton.setForeground(java.awt.SystemColor.activeCaption);
        InfoButton.setText("?");
        InfoButton.setBorder(null);
        InfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(APPLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(Error2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(Error3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(CantidadText, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Error4, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DistribuidorLabel)
                                        .addGap(19, 19, 19)
                                        .addComponent(OpcionDistribuidor1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(OpcionDistribuidor2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(OpcionDistribuidor3))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(Error1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TipoMedicamentoBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(NombreMedicamentoText)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Error5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FarmaciaLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(Farmacia1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Farmacia2)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(APPLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NombreMedicamentoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InfoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Error1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TipoMedicamentoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(3, 3, 3)
                .addComponent(Error2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CantidadText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Error3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DistribuidorLabel)
                    .addComponent(OpcionDistribuidor1)
                    .addComponent(OpcionDistribuidor2)
                    .addComponent(OpcionDistribuidor3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Error4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Farmacia1)
                    .addComponent(Farmacia2)
                    .addComponent(FarmaciaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Error5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CantidadTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadTextActionPerformed

    }//GEN-LAST:event_CantidadTextActionPerformed

    private void OpcionDistribuidor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcionDistribuidor1ActionPerformed

    }//GEN-LAST:event_OpcionDistribuidor1ActionPerformed

    private void TipoMedicamentoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoMedicamentoBoxActionPerformed

    }//GEN-LAST:event_TipoMedicamentoBoxActionPerformed

    private void NombreMedicamentoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreMedicamentoTextActionPerformed

    }//GEN-LAST:event_NombreMedicamentoTextActionPerformed
    /**
     * Este método es llamado cuando se presiona el botón "Borrar".
     * Restablece todos los campos y errores a su estado inicial.
     * @param evt Evento de acción.
     */
    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed

        NombreMedicamentoText.setText("");

        CantidadText.setText("");

        TipoMedicamentoBox.setSelectedIndex(0);

        buttonGroup1.clearSelection();

        Farmacia1.setSelected(false);
        Farmacia2.setSelected(false);

        if (Error1.isVisible()) {
            Error1.setText("");
            Error1.setVisible(false);
            NombreMedicamentoText.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }
        if (Error2.isVisible()) {
            Error2.setText("");
            Error2.setVisible(false);
            TipoMedicamentoBox.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }
        if (Error3.isVisible()) {
            Error3.setText("");
            Error3.setVisible(false);
            CantidadText.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }
        if (Error4.isVisible()) {
            Error4.setText("");
            Error3.setVisible(false);
        }
        if (Error5.isVisible()) {
            Error5.setText("");
            Error5.setVisible(false);
        }

    }//GEN-LAST:event_CancelButtonActionPerformed
    /**
     * Este método es llamado cuando se presiona el botón "CONFIRMAR".
     * Realiza validaciones de campos y muestra el formulario de resumen si los datos son válidos.
     * @param evt Evento de acción.
     */
    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        // Condiciones para el nombre del medicamento
        String nombreMedicamento = NombreMedicamentoText.getText();
        if (nombreMedicamento.isEmpty()) {
            Error1.setText("Debe introducir un nombre");
            Error1.setForeground(Color.RED);
            Error1.setVisible(true);
            NombreMedicamentoText.setBorder(BorderFactory.createLineBorder(Color.RED));
        } else if (!nombreMedicamento.matches("^[a-zA-Z0-9\\s]+$")) {
            Error1.setText("Caracteres aceptados: [a-z, A-Z, 0-9].");
            Error1.setForeground(Color.RED);
            Error1.setVisible(true);
            NombreMedicamentoText.setBorder(BorderFactory.createLineBorder(Color.RED));
        } else if (nombreMedicamento.length() < 3) {
            Error1.setText("El número mínimo de caracteres es de 3");
            Error1.setForeground(Color.RED);
            Error1.setVisible(true);
            NombreMedicamentoText.setBorder(BorderFactory.createLineBorder(Color.RED));
        }else{
            Error1.setVisible(false);
            NombreMedicamentoText.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }

        // Condiciones para el tipo de medicamento
        int indiceSeleccionado = TipoMedicamentoBox.getSelectedIndex();
        if (indiceSeleccionado == 0) {
            Error2.setText("Debe escoger un tipo de medicamento");
            Error2.setForeground(Color.RED);
            Error2.setVisible(true);
            TipoMedicamentoBox.setBorder(BorderFactory.createLineBorder(Color.RED));
        } else {
            Error2.setVisible(false);
            TipoMedicamentoBox.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }
        String tipoMedicamento = (String) TipoMedicamentoBox.getSelectedItem();
        // Condiciones de la cantidad
        String cantidadElegida = CantidadText.getText();
        
        if (cantidadElegida.isEmpty()) {
            CantidadText.setText("0");
        }
        if (cantidadElegida.isEmpty() || cantidadElegida.equals("00")|| cantidadElegida.equals("00")||cantidadElegida.equals("000")) {
            Error3.setText("Debe introducir una cantidad válida");
            Error3.setForeground(Color.RED);
            Error3.setVisible(true);
            CantidadText.setBorder(BorderFactory.createLineBorder(Color.RED));
            
        } else {
            Error3.setVisible(false);
            CantidadText.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        }

        // Condiciones del distribuidor
        if (!OpcionDistribuidor1.isSelected() && !OpcionDistribuidor2.isSelected() && !OpcionDistribuidor3.isSelected()) {
            Error4.setText("Debe seleccionar un distribuidor");
            Error4.setForeground(Color.RED);
            Error4.setVisible(true);
        } else {
            Error4.setVisible(false);
        }

        // Condiciones de Farmacia
        if (!Farmacia1.isSelected() && !Farmacia2.isSelected()) {
            Error5.setText("Debe seleccionar la/s farmacia/s destino");
            Error5.setForeground(Color.RED);
            Error5.setVisible(true);
            return;
        } else {
            Error5.setVisible(false);
        }

        //Informacion a mostrar en el segundo formulario
        //Distribuidor
        String distribuidor = "";
        if (OpcionDistribuidor1.isSelected()) {
            distribuidor = "Cofarma";
        } else if (OpcionDistribuidor2.isSelected()) {
            distribuidor = "Empsephar";
        } else if (OpcionDistribuidor3.isSelected()) {
            distribuidor = "Cemefar";
        }
        //Cantidad
        int cantidad = Integer.parseInt(cantidadElegida);
        //Direccion
        String direccion = "";
        if (Farmacia1.isSelected()) {
            direccion += "Calle de la Rosa n. 28 ";
        }
        if (Farmacia2.isSelected()) {
            if (!direccion.isEmpty()) {
                direccion += "y ";
            }
            direccion += "Calle Alcazabilla n. 3";
        }
        //Si ninguno de los campos esta vaccio, permite abrir el segundo formulario.
        if (!NombreMedicamentoText.getText().isEmpty() && NombreMedicamentoText.getText().length() >= 3
                && !CantidadText.getText().isEmpty() && !CantidadText.getText().equals("0") && !CantidadText.getText().equals("00") && !CantidadText.getText().equals("000")
                && TipoMedicamentoBox.getSelectedIndex() != 0
                && (OpcionDistribuidor1.isSelected() || OpcionDistribuidor2.isSelected() || OpcionDistribuidor3.isSelected())
                && (Farmacia1.isSelected() || Farmacia2.isSelected())) {
            new FormularioResumen(distribuidor, cantidad, tipoMedicamento, nombreMedicamento, direccion).setVisible(true);
            this.setVisible(false);
        }


    }//GEN-LAST:event_NextButtonActionPerformed

    private void InfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoButtonActionPerformed
        JOptionPane.showMessageDialog(null, "Ha de tener en cuenta que debe introducir un nombre de medicamento válido y reconocible. De no hacerlo, el distribuidor podría anular el pedido.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_InfoButtonActionPerformed

    /**
     * Método principal que inicia la aplicación.
     * @param args Argumentos de la línea de comandos.
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel APPLabel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField CantidadText;
    private javax.swing.JLabel DistribuidorLabel;
    private javax.swing.JLabel Error1;
    private javax.swing.JLabel Error2;
    private javax.swing.JLabel Error3;
    private javax.swing.JLabel Error4;
    private javax.swing.JLabel Error5;
    private javax.swing.JCheckBox Farmacia1;
    private javax.swing.JCheckBox Farmacia2;
    private javax.swing.JLabel FarmaciaLabel;
    private javax.swing.JButton InfoButton;
    private javax.swing.JButton NextButton;
    private javax.swing.JTextField NombreMedicamentoText;
    private javax.swing.JRadioButton OpcionDistribuidor1;
    private javax.swing.JRadioButton OpcionDistribuidor2;
    private javax.swing.JRadioButton OpcionDistribuidor3;
    private javax.swing.JComboBox<String> TipoMedicamentoBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
